name: Monitor Price Change

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  monitor_price:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests

      - name: Run Python script
        run: python .github/scripts/monitor_price.py
